version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: '${{secrets.PACKAGE_ACCESS}}'

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
    target-branch: 'main'
    open-pull-requests-limit: 100
    groups:
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    target-branch: 'main'
    allow:
      - dependency-name: '@org/*'
    labels:
      - dependencies
    registries:
      - npm-registry-npm-pkg-github-com
    open-pull-requests-limit: 100
