name: CI - integration test yarn berry

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

# Use the currently executing project name in your command.:
# yarn nx affected -t build --tag=$NX_TASK_TARGET_PROJECT:latest
# yarn nx affected -t release --exclude='*,!tag:latest'
jobs:
  main:
    name: Release package
    uses: ./.github/workflows/nx-cloud-main.yml
    with:
      working-directory: ./integration-tests/yarn-berry
      parallel-commands: |
        yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected -t build --parallel=1 --tag=$NX_TASK_TARGET_PROJECT:latest
        yarn nx affected -t lint --parallel=1
        yarn nx affected -t test --parallel=1 --ci --code-coverage
        yarn nx affected -t validate --parallel=1
        yarn nx affected -t release --parallel=1

  agents:
    name: Nx Cloud - Agents
    uses: ./.github/workflows/nx-cloud-agents.yml
    with:
      working-directory: ./integration-tests/yarn-berry
      number-of-agents: 3
